language: php
services:
  - mysql
php:
  - 7.1
  - 7.2
  - 7.3
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql -e "create database test;use test; CREATE TABLE address (id int(11) NOT NULL AUTO_INCREMENT,name varchar(32),enname varchar(64) ,acronym varchar(12),code varchar(21) ,add_time int(11) ,PRIMARY KEY (id));"
  - sudo service mysql restart
  
before_script:
  - composer install --dev
script: 
  - cd tests
  - ../vendor/bin/phpunit -v
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v
  - set ig71=$(php -v | grep "PHP 7.1");
  - if [ -z "$ig71" ]; then cd ext && phpize && ./configure && make && make install && cd .. && echo "extension=entity.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd tests && ../vendor/bin/phpunit -v; fi
  
  
  
  
